version: "3"

services:
  ssh:
    image: mr14mr/alpine-openssh:latest
    build:
      context: .
    ports:
      - "2222:22"
    volumes:
      - ./authorized_keys:/root/.ssh/authorized_keys
    networks:
      - ssh
      - backend

  # Wiki starts here
  database:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  app:
    image: hackmdio/hackmd:1.3.1-alpine
    environment:
      - HMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
    ports:
      - "3000"
    networks:
      - backend
    restart: always
    depends_on:
      - database

networks:
  backend:
    internal: true
    driver: bridge
  ssh:


volumes:
  database:


